name: Matlab actions
on: [push]
jobs:
  my-job:
    name: testing name here
    runs-on: windows-latest
    steps:
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2.3.0

            
